import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#e2e2e5",
        "inverse-surface": "#2f3133",
        "surface-dim": "#dadadc",
        "on-primary-fixed-variant": "#92001d",
        "primary-fixed-dim": "#ffb3b1",
        "primary-container": "#e31837",
        "on-tertiary-fixed-variant": "#004f57",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#77d4e1",
        "surface-container-high": "#e8e8ea",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdad8",
        "tertiary-container": "#00808c",
        "error-container": "#ffdad6",
        outline: "#916e6d",
        "on-primary-container": "#fffaf9",
        error: "#ba1a1a",
        background: "#f9f9fc",
        "surface-bright": "#f9f9fc",
        "surface-container": "#eeeef0",
        secondary: "#5d5e61",
        "on-secondary-container": "#636467",
        "surface-container-highest": "#e2e2e5",
        "on-error": "#ffffff",
        "surface-tint": "#bf0029",
        tertiary: "#00656f",
        "outline-variant": "#e6bdbb",
        "on-surface": "#1a1c1e",
        surface: "#f9f9fc",
        "inverse-on-surface": "#f0f0f3",
        "secondary-fixed": "#e2e2e5",
        "tertiary-fixed": "#93f1fe",
        "on-tertiary-fixed": "#001f23",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#410007",
        primary: "#b90027",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f2fdff",
        "on-surface-variant": "#5d3f3e",
        "on-secondary-fixed-variant": "#454749",
        "surface-container-low": "#f3f3f6",
        "inverse-primary": "#ffb3b1",
        "on-background": "#1a1c1e",
        "secondary-fixed-dim": "#c6c6c9",
        "on-secondary-fixed": "#1a1c1e",
        "surface-variant": "#e2e2e5",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-plus-jakarta)", "system-ui", "sans-serif"],
        body: ["var(--font-plus-jakarta)", "system-ui", "sans-serif"],
        label: ["var(--font-inter)", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
} satisfies Config;
